FROM buildpack-deps:jessie
ENV LANG C.UTF-8

RUN (curl -sL https://deb.nodesource.com/setup_6.x | bash -) && \
    apt-get install -y \
    nodejs \
 && rm -rf /var/lib/apt/lists/*

ENV APP_DIR /app
RUN mkdir -p $APP_DIR
WORKDIR ${APP_DIR}
